const themes = [
  "Friendship",
  "Pets",
  "Hobbies",
  "Travel",
  "Food and Cooking",
  "Books and Reading",
  "Music",
  "Movies and TV Shows",
  "Sports",
  "Nature",
  "Technology",
  "Health and Wellness",
  "Education",
  "Family",
  "Work and Career",
  "Holidays and Celebrations",
  "Art and Creativity",
  "Fashion and Style",
  "Home and Living",
  "Relationships",
  "Community",
  "Culture and Diversity",
  "History and Heritage",
  "Mindfulness and Self-care",
  "Adventure",
  "Dreams and Aspirations",
  "Volunteering and Charity",
  "Learning and Growth",
  "Environment",
  "Finance and Budgeting",
  "Gardening",
  "Weather",
  "Humor and Laughter",
  "Social Media",
  "Current Events",
  "Self-Expression",
  "Reflection and Gratitude",
  "Communication",
  "Childhood Memories",
  "Creativity",
  "Inspiration",
  "Motivation",
  "Challenges and Resilience",
  "Community Service",
  "Random Acts of Kindness",
  "Outdoor Activities",
  "Healthy Living",
  "Family Traditions",
  "Learning from Mistakes",
  "Cultural Celebrations",
];

export default themes;
